#!/bin/bash
# Configuring domain zone so that the subdomain www points to load-balancer IP (lb-01).

get_record_info() {
  local domain=$1
  local subdomain=$2
  local record_info=$(dig $subdomain.$domain | awk '/ANSWER SECTION/{getline; print}')
  
  local record_type=$(echo $record_info | awk '{print $4}')
  local destination=$(echo $record_info | awk '{print $5}')
  echo "The subdomain $subdomain is a $record_type record and points to $destination"

}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")

else
  subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
  get_record_info $domain $sub

done
