#!/bin/bash
# Configuring domain zone so that the subdomain www points to load-balancer IP (lb-01)

#!/bin/bash

get_dns_info() {
  domain=$1
  subdomain=$2

  if [[ -n $subdomain ]]; then
    record_info=$(dig "$subdomain.$domain" | awk '/^'"$subdomain.$domain"'/ { getline; print }')
    echo "The subdomain $subdomain is a $record_info"
  else
    subdomains=("www" "54.157.167.244" "52.3.220.1" "52.91.124.243")
    for sub in "${subdomains[@]}"; do
      record_info=$(dig "$sub.$domain" | awk '/^'"$sub.$domain"'/ { getline; print }')
      echo "The subdomain $sub is a A $record_info and points to $destination"
    done
  fi
}

get_dns_info "$1" "$2"



domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
  subdomains=("www" "54.157.167.244" "52.3.220.1" "52.91.124.243")
else
  subdomains=("$subdomain")
fi
    
for sub in "${subdomains[@]}"; do
  result=$(dig "$sub.$domain" +short)
  if [[ -n "$result" ]]; then
    echo "The subdomain $sub is a A record and points to $result"

  fi
done
