#!/usr/bin/env bash
# Script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
  echo "Usage: 0-tranfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

export "SCP_OPTIONS=-o StrictHostKeyChecking=no"
scp -i "$ssh_key" "file_path" "username@$server_ip:~/"

if [ "$?" -eq 0 ]; then
  echo "File transfer completed successfully."
else
  echo "File transfer failed."
fi
