#!/usr/bin/env bash
# This script installs and configures Nginx to
# listen on port 80 and return a "Hello World!" page

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a backup of the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Modify the default configuration file to listen on port 80 and return "Hello World!"
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        location / {
                echo 'Hello World!';
        }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo kill -s HUP $(cat /var/run/nginx.pid)
