#!/usr/bin/env bash
# This script set up replication on the replica.

STOP SLAVE;
CHANGE MASTER TO MASTER_HOST='web-01',
MASTER_USER='replica_user',
MASTER_PASSWORD='04035456',
MASTER_LOG_FILE='mysql-bin.000001',
MASTER_LOG_POS=0;
START SLAVE;

