#!/usr/bin/env bash
#Display "Best School" times 10,
# but for the 9th iteration, displays Best School and then Hi on a new line.

count=0

while [ $count -lt 10 ]

do
	if [ $count -eq 9 ]

	then
		echo "Hi"
	fi

	echo "Best School"
	(( count++ ))
done

