#!/usr/bin/env bash
# This sript runs the whoami command under
# the  user passed as an argument

# Check if argument is provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Get username from the first argument
username="$1"

# Runthe whoami command under the specified user
if id "$username" &>/dev/null; then
  sudo -u "$username" whoami
else
  echo "Error: User $username does not exist"
  exit 1
fi
