#!/usr/bin/env bash
# This script to configure Nginx to run as
# the nginx user and listen on port 8080

sed -i 's/user\s\+.*;/user nginx;/' /etc/nginx/nginx.conf

# Check if the default server configuration exists
default_server_config="/etc/nginx/conf.d/default.conf"

if [ -f "$default_server_config" ]; then

  sed -i '/listen\s\+80;/a \    listen 8080 default_server;' "$default_server_config"
fi

# Restart Nginx service to apply the changes
service nginx restart
