#!/usr/bin/env bash
# This script to configure Nginx to run as
# the nginx user and listen on port 8080

# Updating Nginx configuration to run as nginx user
sed -i 's/user\s\+.*;/user nginx;/' /etc/nginx/nginx.conf

default_server_config="/etc/nginx/conf.d/default.conf"
if [ -f "$default_server_config" ]; then
  # Update Nginx default server configuration to listen on all active IPs on port 8080
  sed -i '/listen\s\+80;/a \    listen 8080 default_server;' "$default_server_config"
fi

# Restarting Nginx service
service nginx restart

